CREATE TABLE fornecedores (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 nome VARCHAR(180) NOT NULL,
 nuit VARCHAR(30) NULL,
 email VARCHAR(150) NULL,
 telefone VARCHAR(30) NULL,
 pais VARCHAR(100) NULL,
 endereco VARCHAR(255) NULL,
 observacoes TEXT NULL,
 estado ENUM('ativo','inativo') NOT NULL DEFAULT 'ativo',
 created_by INT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX(nome),INDEX(estado),
 FOREIGN KEY(created_by) REFERENCES utilizadores(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE solicitacoes (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 cliente_id INT UNSIGNED NOT NULL,
 titulo VARCHAR(180) NOT NULL,
 descricao TEXT NOT NULL,
 referencia VARCHAR(255) NULL,
 quantidade DECIMAL(15,3) NOT NULL DEFAULT 1,
 origem ENUM('local','africa_sul','outro') NOT NULL DEFAULT 'local',
 estado ENUM('nova','em_pesquisa','cotada','aprovada','cancelada','concluida') NOT NULL DEFAULT 'nova',
 created_by INT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT,
 FOREIGN KEY(created_by) REFERENCES utilizadores(id) ON DELETE SET NULL,
 INDEX(estado),INDEX(cliente_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cotacoes (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 cliente_id INT UNSIGNED NOT NULL,
 solicitacao_id INT UNSIGNED NULL,
 descricao VARCHAR(255) NOT NULL,
 subtotal DECIMAL(15,2) NOT NULL DEFAULT 0,
 custo_logistica DECIMAL(15,2) NOT NULL DEFAULT 0,
 outros_custos DECIMAL(15,2) NOT NULL DEFAULT 0,
 margem DECIMAL(15,2) NOT NULL DEFAULT 0,
 entrega DECIMAL(15,2) NOT NULL DEFAULT 0,
 total DECIMAL(15,2) NOT NULL DEFAULT 0,
 validade DATE NULL,
 estado ENUM('rascunho','enviada','aprovada','rejeitada','expirada') NOT NULL DEFAULT 'rascunho',
 observacoes TEXT NULL,
 created_by INT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(cliente_id) REFERENCES clientes(id) ON DELETE RESTRICT,
 FOREIGN KEY(solicitacao_id) REFERENCES solicitacoes(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES utilizadores(id) ON DELETE SET NULL,
 INDEX(cliente_id),INDEX(estado)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
