<?php
namespace Wortek\Store\Repositories;
use PDO; use Throwable;
final class OrderRepository {
 public function __construct(private PDO $pdo){}
 public function all(): array { return $this->pdo->query('SELECT p.*,c.nome AS cliente_nome FROM pedidos p JOIN clientes c ON c.id=p.cliente_id ORDER BY p.id DESC')->fetchAll(); }
 public function find(int $id): ?array { $s=$this->pdo->prepare('SELECT p.*,c.nome AS cliente_nome FROM pedidos p JOIN clientes c ON c.id=p.cliente_id WHERE p.id=:id');$s->execute(['id'=>$id]);$r=$s->fetch();if(!$r)return null;$i=$this->pdo->prepare('SELECT pi.*,pr.sku,pr.nome produto_nome FROM pedido_itens pi LEFT JOIN produtos pr ON pr.id=pi.produto_id WHERE pi.pedido_id=:id ORDER BY pi.id');$i->execute(['id'=>$id]);$r['itens']=$i->fetchAll();return $r; }
 public function create(array $d,array $items,int $userId): int { $this->pdo->beginTransaction();try{$numero='PED-'.date('Ymd-His').'-'.random_int(100,999);$subtotal=0;foreach($items as $it)$subtotal+=(float)$it['quantidade']*(float)$it['preco_unitario'];$entrega=(float)($d['entrega']??0);$desconto=(float)($d['desconto']??0);$total=$subtotal+$entrega-$desconto;$s=$this->pdo->prepare('INSERT INTO pedidos(numero,cliente_id,tipo,estado,subtotal,entrega,desconto,total,observacoes,created_by) VALUES(:numero,:cliente_id,:tipo,:estado,:subtotal,:entrega,:desconto,:total,:observacoes,:created_by)');$s->execute(['numero'=>$numero,'cliente_id'=>$d['cliente_id'],'tipo'=>$d['tipo']??'stock','estado'=>$d['estado']??'rascunho','subtotal'=>$subtotal,'entrega'=>$entrega,'desconto'=>$desconto,'total'=>$total,'observacoes'=>$d['observacoes']??null,'created_by'=>$userId]);$id=(int)$this->pdo->lastInsertId();$si=$this->pdo->prepare('INSERT INTO pedido_itens(pedido_id,produto_id,descricao,quantidade,preco_unitario,total) VALUES(:pedido_id,:produto_id,:descricao,:quantidade,:preco_unitario,:total)');foreach($items as $it){$q=(float)$it['quantidade'];$p=(float)$it['preco_unitario'];$si->execute(['pedido_id'=>$id,'produto_id'=>$it['produto_id']??null,'descricao'=>$it['descricao'],'quantidade'=>$q,'preco_unitario'=>$p,'total'=>$q*$p]);}$this->pdo->commit();return $id;}catch(Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;} }
 public function updateStatus(int $id,string $status): void { $s=$this->pdo->prepare('UPDATE pedidos SET estado=:e WHERE id=:id');$s->execute(['e'=>$status,'id'=>$id]); }
}
